### ISSUE TITLE
Null is not supported by swagger spec

### ISSUE THREAD

**Issue by cbornet** [sendgrid/sendgrid-oai#10]
I tried http://petstore.swagger.io/?url=https://raw.githubusercontent.com/sendgrid/sendgrid-oai/master/oai.json
You can see that it fails because the def contains "null" types which is not supported by the OAI spec at the moment (see https://github.com/OAI/OpenAPI-Specification/issues/229)

**Comment by thinkingserious** [comment]
Thank you @cbornet! We will take a look.

**Comment by pytlesk4** [comment]
Interesting!  If you go to [Swagger Editor](http://editor.swagger.io/), there are no errors.  Also, I could be misreading the swagger spec, but I think JSON-Schema types of null are fine: [Schema Object](http://swagger.io/specification/#schemaObject).

The important part above is: 

- The following properties are taken directly from the JSON Schema definition and follow the same specifications

And JSON Schema 4 says: [JSON Schema v4](http://json-schema.org/latest/json-schema-core.html#anchor8), which says null is valid.

I could be mistaken, but according to the swagger spec: [Parameter Object](http://swagger.io/specification/#parameterObject), a parameter object can't have a null type.

**Comment by cbornet** [comment]
See [my comment](https://github.com/OAI/OpenAPI-Specification/issues/229#issuecomment-221532669)

**Comment by thinkingserious** [comment]
@cbornet, @pytlesk4,

Thanks for the continued feedback and conversation!

@cbornet,

Do you mind sharing your use case and how our currently formatted oai.json file is breaking your solution?

Thanks!

**Comment by cbornet** [comment]
It breaks at least with [swagger-ui](http://swagger.io/swagger-ui/) (see http://petstore.swagger.io/?url=https://raw.githubusercontent.com/sendgrid/sendgrid-oai/master/oai.json).

**Comment by thinkingserious** [comment]
@cbornet Thanks!

**Comment by thinkingserious** [comment]
Please see: https://github.com/sendgrid/sendgrid-oai/issues/10 for follow up
