### ISSUE TITLE
Swagger.json File for Sendgrid 

### ISSUE THREAD

**Issue by mag-hub** [sendgrid/sendgrid-oai#100]
### Issue Summary
We are planning to integrate the Sendgrid with Salesforce using external services and named credentials. In the case of External Service in Salesforce, we will need to provide "Swagger File" or "Service Schema Relative URL" of Sendgrid API. We didn't find this file or URL in any Public documentation released by Sendgrid.

However, we found one unpublished swagger file for Sendgrid on one forum [https://app.swaggerhub.com/apis/yuki-teraoka/send-grid_v_3_api_documentation/3.0]. We would like to request an updated swagger.json file or please confirm if we can proceed with the file we found on the forum.

**Comment by shwetha-manvinkurke** [comment]
It's still WIP but [here's](https://github.com/sendgrid/sendgrid-oai/blob/main/oai_v3_stoplight.json) one for reference

**Comment by mag-hub** [comment]
Thank You, it will be helpful.
