### ISSUE TITLE
Prism and version URLs

### ISSUE THREAD

**Issue by lfolco** [sendgrid/sendgrid-oai#103]
I am trying to use Prism as a mock server for testing. I am running it like so:

```
prism mock https://raw.githubusercontent.com/sendgrid/sendgrid-oai/main/oai_v3_stoplight.json
```

The issue is, the when I use the SendGrid PHP library to call it, it's expecting to see a url prefixed with `v3`, so I am getting errors:

```
post /v3/mail/send ✖  error     Request terminated with error: https://stoplight.io/prism/errors#NO_PATH_MATCHED_ERROR: Route not resolved, no path matched
```

Sorry if this is the wrong forum to ask this, wasn't sure if I should ask here or https://github.com/sendgrid/sendgrid-php.

**Comment by shwetha-manvinkurke** [comment]
Hi @lfolco, the v3 spec is still a WIP and we are aware of the said issue. Have you tried bumping down the prism version to 2.x.x and try mocking with `oai_stoplight.json` instead?

**Comment by lfolco** [comment]
I'm not seeing the ability to install Prism below v3, any idea of when this could be resolved? 2.x is quite old.

**Comment by astuteape** [comment]
Hi @lfolco, as @shwetha-manvinkurke noted, v3 is still a work in progress, and some more changes are coming soon. It looks like we're missing the `servers` array to set a base path in the spec. We've noted it and hope to have a fix out soon. Thanks for calling it to our attention.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-oai/pull/112
