### ISSUE TITLE
Invalid URL to sendgrid logo

### ISSUE THREAD

**Issue by IvanGoncharov** [sendgrid/sendgrid-oai#11]
In README you use the following URL to logo:
https://assets3.sendgrid.com/mkt/assets/logos_brands/small/sglogo_2015_blue-9c87423c2ff2ff393ebce1ab3bd018a4.png
Currently, it returns 404 error, but it still showed in README because Github uses proxy.
This is very important for me since I use this logo in my catalog.
It would be great if you host logo directly inside the repo.

**Comment by thinkingserious** [comment]
Thanks for letting us know, we will get this updated.

Internal note: 
https://sendgrid.com/resource/brand/
