### ISSUE TITLE
Question: Contribution to v3 API docs

### ISSUE THREAD

**Issue by gabrielkrell** [sendgrid/sendgrid-oai#25]
Hey guys! While working on an issue elsewhere I found a few typos in the [Stoplight API docs](https://sendgrid.com/docs/API_Reference/api_v3.html).  If I bundle those up into a PR, can you easily merge them in?  It looks like code commits to this repo are autogenerated from Stoplight, so I wanted to ask.  If not, is there another way to submit changes?

**Comment by Whatthefoxsays** [comment]
Hi @gabrielkrell! Just go ahead and comment here and we'll get the changes merged in! Thanks for your help!
