### ISSUE TITLE
[Question] Public swagger ui instance to access this API

### ISSUE THREAD

**Issue by KevinSheedy** [sendgrid/sendgrid-oai#3]
Hi
I want to access the sendgrid API using swagger ui.
Do you know of a public swagger ui instance that can be used?

I tried using the [public swagger.io instance](http://petstore.swagger.io/) and gave it your [swagger.json](https://rawgit.com/sendgrid/sendgrid-swagger/master/swagger.json) file. However, swagger doesn't send the necessary header required to get access to the API

```
Authorization: Bearer API_KEY
```

Do you know of an instance of swagger ui that will send this header? Or do I need to modify the swagger ui code myself?

Thanks

**Comment by mbernier** [comment]
I don't know enough about SwaggerUI specifically to answer this question directly. 

In Postman, we have to just add an Authorization header to the headers area itself.

I hope this helps! 

(Also, you should be able to import this schema into Postman, which is free, if you'd like)

**Comment by KevinSheedy** [comment]
Here's a demo of what I mean:
http://kevinsheedy.github.io/sendgrid-swagger-ui/dist/

Basically, I think it would be very useful to be able to access the SendGrid api using a public instance of swagger ui. However, it's failing on the CORS Preflight check, getting a 307 Internal Redirect:

```
Request URL:http://api.sendgrid.com/v3/templates
Request Method:OPTIONS
Status Code:307 Internal Redirect

Response Headers
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://kevinsheedy.github.io
Location:https://api.sendgrid.com/v3/templates
Non-Authoritative-Reason:HSTS

Request Headers
Provisional headers are shown
Access-Control-Request-Headers:accept, authorization
Access-Control-Request-Method:GET
Origin:http://kevinsheedy.github.io
Referer:http://kevinsheedy.github.io/sendgrid-swagger-ui/dist/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
```

Any thoughts/ideas?

**Comment by mbernier** [comment]
Ahh, thank you so much. I apologize, the CORS issue is a known thing and we are absolutely working on it. I will send this note along with the others to see what I can do to keep this moving along. 

Thank you!

**Comment by mbernier** [comment]
This is currently being worked on!! It should be fixed soon. Sorry for the delay!

**Comment by mbernier** [comment]
@KevinSheedy I have to apologize, I lost track of this thread. 

In the meantime, we went around and around with our infosec team - long story short, we ended up making a completely interactive version of our documentation that has a specific CORS header. 

You can check it out here: https://sendgrid.com/docs/API_Reference/api_v3.html

Also, if you would like to use our OAI file within Postman, that should work as well!
