### ISSUE TITLE
Run our *.md documents in this repo through the Grammer.ly service and update

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-oai#51]
#### Issue Summary

We would like to get our English polished up throughout the repo.

#### Aceptance Criteria

* Every .md file in this repo has been run through the Grammer.ly service and updated accordingly

**Comment by MisterJack49** [comment]
Hi can I grab this issue ?

**Comment by thinkingserious** [comment]
It's all yours @MisterJack49, thanks!

**Comment by childish-sambino** [comment]
Fixed by #52
