### ISSUE TITLE
CONTRIBUTING.md broken link

### ISSUE THREAD

**Issue by arshadkazmi42** [sendgrid/sendgrid-oai#53]
#### Issue Summary

Issue template link is broken in [CONTRIBUTING.md](https://github.com/sendgrid/sendgrid-oai/blob/master/CONTRIBUTING.md#please-use-our-bug-report-template)

Clicking on `sample bug report template`  redirects to 404 page.

#### Steps to Reproduce

1. Go to [CONTRIBUTING.md](https://github.com/sendgrid/sendgrid-oai/blob/master/CONTRIBUTING.md#please-use-our-bug-report-template)
2. Click on `sample bug report template`

**Comment by arshadkazmi42** [comment]
working on fixing this.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-oai/commit/49f9dc6b39dcf946a5f140476d2c57054d5c7d75
