### ISSUE TITLE
(oai_stoplight) Mock server verification

### ISSUE THREAD

**Issue by aleien** [sendgrid/sendgrid-oai#62]
#### Issue Summary

Hello!
I wanted to participate by helping with issue https://github.com/sendgrid/sendgrid-go/issues/255
But one of the requirements there is to write a test, that will show example with error from /templates/{template_id}
But there is no such description there. Moreover, I am not sure that it's possible with current solution for mock server to validate request and choose between successful and unsuccessful results.

Is it possible for you to implement such verification ability to mock server? Or maybe it's already implemented, and I just didn't found it? (:

Thank you in advance.

**Comment by thinkingserious** [comment]
Hello @aleien,

I believe you will need to use StopLight Prism's [scripting functionality](https://help.stoplight.io/prism/examples/response?utm_source=github&utm_medium=prism) for that.

With Best Regards,

Elmer
