### ISSUE TITLE
send mail & substitutions

### ISSUE THREAD

**Issue by bpapineau** [sendgrid/sendgrid-oai#69]
I'm not sure is the best place to post this bug; don't hesitate to move it or explain to me where put this post.

The problem come from https://api.sendgrid.com/api/mail.send.xml

For an unknown reason, sometimes, when we use substitution in order to send emails, the substitution doesn't work for one or many fields.

I have request and response contents, but it contains business stuff, so do you have an email in order to send you the POST request ?

**Comment by thinkingserious** [comment]
Hello @bpapineau,

Thanks for reaching out! The best place to file this issue would be with our [support team](https://support.sendgrid.com).

Thank you!

With Best Regards,

Elmer

**Comment by bpapineau** [comment]
Elmer,

Your Support Team ask me to contact you via Github :(

I don't know where explain my problem... >_<

**Comment by thinkingserious** [comment]
@bpapineau,

Perhaps you may find luck using one of our SDKs. What language is your application developed in?

With Best Regards,

Elmer
