### ISSUE TITLE
Object with empty property name

### ISSUE THREAD

**Issue by IvanGoncharov** [sendgrid/sendgrid-oai#7]
Reported by @sergey-tihon as https://github.com/APIs-guru/api-models/issues/56

Object with empty property name, see:
https://github.com/sendgrid/sendgrid-swagger/blob/master/swagger.yaml#L10583-L10584
You probably meant `hash`, to do this in JSON Schema you should use `additionalProperties`, see:
http://json-schema.org/latest/json-schema-validation.html#anchor64

**Comment by thinkingserious** [comment]
Thanks! We've added this to our backlog.

**Comment by IvanGoncharov** [comment]
@thinkingserious Any progress on this?
Does it make sense if I submit PR or Swagger files autogenerated?

**Comment by thinkingserious** [comment]
@IvanGoncharov feel free to submit a PR, so I can then add the change in our automation workflow.

Thanks!

**Comment by mbernier** [comment]
@IvanGoncharov can you please inspect the file again and see if this is still an issue?

**Comment by IvanGoncharov** [comment]
@mbernier Yes, it still is 😞 
Just search for `'':` in YAML or `"":` in JSON.
For example:
```yaml
reply_to:
  description: An email object containing the email address and name of the individual who should receive responses to your email.
  properties:
    '':
      $ref: '#/definitions/email_object'
  type: object
```
To fix this just replace 
```
properties: 
  '':
```
with `additionalProperties`, for example:
```yaml
reply_to:
  description: An email object containing the email address and name of the individual who should receive responses to your email.
  additionalProperties:
    $ref: '#/definitions/email_object'
  type: object
```

**Comment by thinkingserious** [comment]
@IvanGoncharov,

This will be fixed in a few minutes with the next release. Thanks!

**Comment by IvanGoncharov** [comment]
@thinkingserious Thank you 👍
