### ISSUE TITLE
Publish JSON spec

### ISSUE THREAD

**Issue by hoangelos** [sendgrid/sendgrid-oai#71]
To make use of these files you have to checkout the files and use them as a dependency.   This is better than nothing.  However, at least for Python, there’s an openapi client that can ready in spec file and generate a client on the fly.  There’s other discovery tools that can read the spec too.

**Comment by childish-sambino** [comment]
I'm not sure I understand the ask here. Are you wanting this spec published elsewhere, or publishing of actual client libraries that use the spec?
